version: '3'

services:
  #db:
  #  image: postgres
  web:
    build: .
    command: bash -c "pwd && ls && cd starter_project4 && pwd && ls && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_projects
    ports:
      - "8000:8000"
    #depends_on:
    #  - db
